[package]
name = "subnetscan"
version = "1.0.0"
edition = "2024"

[profile.release]
lto = true
strip = true

[dependencies]
colored = "3.0.0"
ipnet = "2.11.0"
rand = "0.9.2"
tokio = { version = "1.48.0", features = ["full"] }
